pom.xml
src/main/java/uk/gov/companieshouse/items/orders/api/ItemType.java
src/main/java/uk/gov/companieshouse/items/orders/api/ItemsApiApplication.java
src/main/java/uk/gov/companieshouse/items/orders/api/controller/CertificateItemsController.java
src/main/java/uk/gov/companieshouse/items/orders/api/dto/CertificateItemDTO.java
src/main/java/uk/gov/companieshouse/items/orders/api/dto/ItemDTO.java
src/main/java/uk/gov/companieshouse/items/orders/api/model/CertificateItemOptions.java
src/main/java/uk/gov/companieshouse/items/orders/api/model/ItemCosts.java
src/main/resources/application.yaml
src/test/java/uk/gov/companieshouse/items/orders/api/ItemTypeUnitTest.java
src/test/java/uk/gov/companieshouse/items/orders/api/controller/CertificateItemsControllerUnitTest.java
src/test/postman/Items_API.postman_collection.json

* Test and implement a controller method to handle a create certificate item request as per the Open API spec at https://developer-specs.kermit.aws.chdev.org/order-company-products/reference/certificates/create.
* No validation, no persistence at this stage.

PCI-451 Implement create request handler that conforms to Open API spec

---

.gitignore
src/main/java/uk/gov/companieshouse/items/orders/api/controller/CertificateItemsController.java
src/main/java/uk/gov/companieshouse/items/orders/api/service/CertificateItemService.java
src/test/java/uk/gov/companieshouse/items/orders/api/controller/CertificateItemsControllerIntegrationTest.java
src/test/java/uk/gov/companieshouse/items/orders/api/service/CertificateItemServiceTest.java

Get certificate item from mongo db
resolves: PCI-467

Pci 467 get items

---

.gitmodules
Makefile
pom.xml
src/main/java/uk/gov/companieshouse/items/orders/api/ItemType.java
src/main/java/uk/gov/companieshouse/items/orders/api/controller/CertificateItemsController.java
src/main/java/uk/gov/companieshouse/items/orders/api/service/CertificateItemService.java
src/main/java/uk/gov/companieshouse/items/orders/api/service/DescriptionProviderService.java
src/test/java/uk/gov/companieshouse/items/orders/api/ItemTypeTest.java
src/test/java/uk/gov/companieshouse/items/orders/api/controller/CertificateItemsControllerIntegrationTest.java
src/test/java/uk/gov/companieshouse/items/orders/api/controller/CertificatesItemControllerTest.java
src/test/java/uk/gov/companieshouse/items/orders/api/service/CertificateItemServiceTest.java
src/test/java/uk/gov/companieshouse/items/orders/api/service/DescriptionProviderServiceTest.java
src/test/resources/api-enumerations/orders_descriptions_incorrect_certificate_descriptions_key.yaml
src/test/resources/api-enumerations/orders_descriptions_incorrect_company_certificate_description_key.yaml

* **NOTE** The changes in this PR depend on the changes to `api-enumerations` that can be seen in its PR https://github.com/companieshouse/api-enumerations/pull/141. `analyse-pull-request` build failure expected for this PR unless or until that `api-enumerations` PR is merged to make the `orders_descriptions.yaml` resource file available to this.

PCI-505: Provide certificate description and description values

---

src/main/java/uk/gov/companieshouse/items/orders/api/config/ApplicationConfiguration.java
src/main/java/uk/gov/companieshouse/items/orders/api/controller/CertificateItemsController.java
src/main/java/uk/gov/companieshouse/items/orders/api/controller/HealthcheckController.java
src/main/resources/application.yaml
src/test/java/uk/gov/companieshouse/items/orders/api/controller/CertificateItemsControllerIntegrationTest.java
src/test/java/uk/gov/companieshouse/items/orders/api/controller/HealthcheckControllerIntegrationTest.java
src/test/resources/application.yaml

added healthcheck
resolves: PCI-603

added healthcheck

---

src/main/java/uk/gov/companieshouse/items/orders/api/dto/CertificateItemDTO.java
src/main/java/uk/gov/companieshouse/items/orders/api/dto/PatchValidationCertificateItemDTO.java
src/test/java/uk/gov/companieshouse/items/orders/api/ItemsApiApplicationTest.java
src/test/java/uk/gov/companieshouse/items/orders/api/controller/CertificateItemsControllerIntegrationTest.java
src/test/postman/Items_API.postman_collection.json

* Change company name validation so that the name is rejected on incoming create/update requests, rather than being required on them.

GCI-791: Company name validation

---

src/main/java/uk/gov/companieshouse/items/orders/api/ItemType.java
src/main/java/uk/gov/companieshouse/items/orders/api/service/DescriptionProviderService.java
src/test/java/uk/gov/companieshouse/items/orders/api/ItemTypeTest.java
src/test/java/uk/gov/companieshouse/items/orders/api/service/DescriptionProviderServiceTest.java

Added description value with key of item type.
resolves: GCI-962

added description value with key of item type

---

src/main/java/uk/gov/companieshouse/items/orders/api/mapper/CertificateItemMapper.java
src/test/java/uk/gov/companieshouse/items/orders/api/mapper/CertificateItemMapperTest.java

This change evaluates request dto to check values of certain fields and adds default values for them if they're missing.

Implement default property setting and tests

---

src/main/java/uk/gov/companieshouse/items/orders/api/service/DescriptionProviderService.java

Removed redundant generic specification from DescriptionProviderService as causing sonar issue

Removed redundant generic specification as causing sonar issue

---

src/main/java/uk/gov/companieshouse/certificates/orders/api/model/ProductType.java

Adds the missing product type `certified-copy-same-day`

Add missing product type

---

pom.xml

Amendments made to upgrade spring boot to 2.1.15.RELEASE. 
Jira ticket - GCI-1268

Spring Boot dependency upgrade

---

src/main/java/uk/gov/companieshouse/certificates/orders/api/model/CertificateType.java
src/main/java/uk/gov/companieshouse/certificates/orders/api/validator/RequestValidator.java
src/test/java/uk/gov/companieshouse/certificates/orders/api/controller/CertificateItemsControllerIntegrationTest.java
src/test/java/uk/gov/companieshouse/certificates/orders/api/validator/CreateItemRequestValidatorTest.java
src/test/java/uk/gov/companieshouse/certificates/orders/api/validator/PatchItemRequestValidatorTest.java
src/test/postman/Certificates_API.postman_collection.json

rename dissolution-liquidation to dissolution
add null checks to request validator for dissolved certificate
update tests to include checks for registered office address, secretary and director details

Allow creation of dissolved certificates and validation

---

pom.xml

Added docker conf to pom file

---

pom.xml
src/main/java/uk/gov/companieshouse/certificates/orders/api/config/ApplicationConfiguration.java
src/main/java/uk/gov/companieshouse/certificates/orders/api/interceptor/UserAuthenticationInterceptor.java
src/main/java/uk/gov/companieshouse/certificates/orders/api/interceptor/UserAuthorisationInterceptor.java
src/test/java/uk/gov/companieshouse/certificates/orders/api/config/ApplicationConfigurationTest.java
src/test/java/uk/gov/companieshouse/certificates/orders/api/config/CostsConfigTest.java
src/test/java/uk/gov/companieshouse/certificates/orders/api/controller/CertificateItemsControllerIntegrationTest.java
src/test/java/uk/gov/companieshouse/certificates/orders/api/util/TestConstants.java

Add interceptor to check that the user has the required token permission
Resolves FA-962, GCI-1556, GCI-1557, GCI-1558

Add interceptor to check token permissions

---

pom.xml

Removed duplicate dependency from pom.xml - api-security-java dependency included on line 90

Removed duplicate dependency

---

src/test/java/uk/gov/companieshouse/certificates/orders/api/CertificatesApiApplicationTest.java

This unit test is currently testing functionality with the `ENABLE_TOKEN_PERMISSION_AUTH` feature flag off (default is off) but the flag is ON in live and it should be testing that behaviour instead. 
Note the feature flag is being removed in #72 and this change will help ensuring nothing breaks.

Amend unit test to work with the new feature flag on

---

src/main/java/uk/gov/companieshouse/certificates/orders/api/controller/CertificateItemsController.java
src/main/java/uk/gov/companieshouse/certificates/orders/api/logging/LoggingConstants.java

Amended logging to include the company number on all end points and the patched company number on patch end point

Amended logging 

---

src/main/java/uk/gov/companieshouse/certificates/orders/api/model/CertificateItemOptions.java
src/main/java/uk/gov/companieshouse/certificates/orders/api/validator/RequestValidator.java
src/test/java/uk/gov/companieshouse/certificates/orders/api/mapper/CertificateItemMapperTest.java
src/test/java/uk/gov/companieshouse/certificates/orders/api/validator/CreateItemRequestValidatorTest.java

* Update validation logic for limited-partnerships
* Add test cases for general nature of business information field
[BI-8941](https://companieshouse.atlassian.net/browse/BI-8941)

BI-8941 Add missing field to item options

---

src/main/java/uk/gov/companieshouse/certificates/orders/api/model/CertificateItemOptions.java
src/main/java/uk/gov/companieshouse/certificates/orders/api/model/PrincipalPlaceOfBusinessDetails.java
src/main/java/uk/gov/companieshouse/certificates/orders/api/validator/RequestValidator.java
src/test/java/uk/gov/companieshouse/certificates/orders/api/mapper/CertificateItemMapperTest.java
src/test/java/uk/gov/companieshouse/certificates/orders/api/validator/CreateItemRequestValidatorTest.java

* Change from using principle to principal
Resolves [BI-9041 Correction to the LP 'Principle' address](https://companieshouse.atlassian.net/browse/BI-9041)

BI-9041 Fix usage of principal and its variants

---

pom.xml
src/main/java/uk/gov/companieshouse/certificates/orders/api/config/FeatureOptions.java
src/main/java/uk/gov/companieshouse/certificates/orders/api/config/FeatureOptionsConfig.java
src/main/java/uk/gov/companieshouse/certificates/orders/api/controller/CertificateItemsController.java
src/main/java/uk/gov/companieshouse/certificates/orders/api/validator/CertificateOptionsValidator.java
src/main/java/uk/gov/companieshouse/certificates/orders/api/validator/CertificateOptionsValidatorConfig.java
src/main/java/uk/gov/companieshouse/certificates/orders/api/validator/CompanyType.java
src/main/java/uk/gov/companieshouse/certificates/orders/api/validator/CreateItemRequestValidator.java
src/main/java/uk/gov/companieshouse/certificates/orders/api/validator/OptionsValidationHelper.java
src/main/java/uk/gov/companieshouse/certificates/orders/api/validator/PatchItemRequestValidator.java
src/main/java/uk/gov/companieshouse/certificates/orders/api/validator/RequestValidator.java
src/main/resources/application.yaml
src/test/java/uk/gov/companieshouse/certificates/orders/api/CertificatesApiApplicationTest.java
src/test/java/uk/gov/companieshouse/certificates/orders/api/controller/CertificateItemsControllerIntegrationTest.java
src/test/java/uk/gov/companieshouse/certificates/orders/api/validator/CertificateOptionsValidatorTest.java
src/test/java/uk/gov/companieshouse/certificates/orders/api/validator/CreateItemRequestValidatorFeatureFlagsDisabledTest.java
src/test/java/uk/gov/companieshouse/certificates/orders/api/validator/CreateItemRequestValidatorFeatureFlagsEnabledTest.java
src/test/java/uk/gov/companieshouse/certificates/orders/api/validator/CreateItemRequestValidatorFlagDisabledTest.java
src/test/java/uk/gov/companieshouse/certificates/orders/api/validator/CreateItemRequestValidatorLLPFeatureFlagEnabledTest.java
src/test/java/uk/gov/companieshouse/certificates/orders/api/validator/CreateItemRequestValidatorLPFeatureFlagEnabledTest.java
src/test/java/uk/gov/companieshouse/certificates/orders/api/validator/CreateItemRequestValidatorTest.java
src/test/java/uk/gov/companieshouse/certificates/orders/api/validator/OptionsValidatorHelperTest.java
src/test/java/uk/gov/companieshouse/certificates/orders/api/validator/PatchItemRequestValidatorTest.java
src/test/resources/application.yaml

- Use feature flags to toggle validation for LP / LLP journeys
[BI-9193](https://companieshouse.atlassian.net/browse/BI-9193)

BI-9193 Add llp and lp feature flags

---

pom.xml
src/main/java/uk/gov/companieshouse/certificates/orders/api/config/MongoConfig.java
src/main/java/uk/gov/companieshouse/certificates/orders/api/controller/CertificateItemsController.java
src/main/resources/application.yaml
src/main/resources/mockito-extensions/org.mockito.plugins.MockMaker
src/test/java/uk/gov/companieshouse/certificates/orders/api/CertificatesApiApplicationTest.java
src/test/java/uk/gov/companieshouse/certificates/orders/api/controller/CertificateItemsControllerIntegrationTest.java
src/test/resources/application.yaml

Update spring boot deps 
Resolves: GCI-1938

Gci 1938 update spring boot

---

pom.xml

bump structured logging dep override log4j version with higher deps
Resolves: DEBT-1426

Security fix for log4j

---

src/main/java/uk/gov/companieshouse/certificates/orders/api/controller/ApiErrors.java
src/test/java/uk/gov/companieshouse/certificates/orders/api/controller/CertificateItemsControllerIntegrationTest.java

* Use correct field name in ApiError
Relates to: [BI-9889Refactor company status and info into an enrichment](https://companieshouse.atlassian.net/browse/BI-9889)

BI-9889 Fix company status error

---

pom.xml
src/test/java/uk/gov/companieshouse/certificates/orders/api/config/AbstractMongoConfig.java
src/test/java/uk/gov/companieshouse/certificates/orders/api/controller/CertificateItemsControllerCreateEndpointIntegrationTest.java
src/test/java/uk/gov/companieshouse/certificates/orders/api/controller/CertificateItemsControllerInitialEndpointIntegrationTest.java
src/test/java/uk/gov/companieshouse/certificates/orders/api/controller/CertificateItemsControllerReadEndpointIntegrationTest.java
src/test/java/uk/gov/companieshouse/certificates/orders/api/controller/CertificateItemsControllerUpdateEndpointIntegrationTest.java
src/test/java/uk/gov/companieshouse/certificates/orders/api/interceptor/UserAuthorisationInterceptorIntegrationTest.java

Remove embedded mongo dependency causing pipeline issues and replace with mongo config and test containers
JU-271

Add test containers

---

pom.xml

modify: jib config for new shared services

---

terraform/groups/ecs-service/profiles/development-eu-west-2/rebel1/vars

Part of MVP for smoke testing mongo:7

Add certificates orders to rebel1

---

pom.xml

Add sonarQube analysis report
